export const USER_INFO_REQUESTED = 'USER_INFO_REQUESTED';
export const USER_INFO_SUCCEEDED = 'USER_INFO_SUCCEEDED';
export const USER_INFO_FAILED = 'USER_INFO_FAILED';
export const LOGOUT_REQUESTED = 'LOGOUT_REQUESTED';
export const LOGOUT_SUCCEEDED = 'LOGOUT_SUCCEEDED';
export const LOGOUT_FAILED = 'LOGOUT_FAILED';

export default {
    USER_INFO_REQUESTED,
    USER_INFO_SUCCEEDED,
    USER_INFO_FAILED,
    LOGOUT_REQUESTED,
    LOGOUT_SUCCEEDED,
    LOGOUT_FAILED
}