//学院
export const GET_COLLEGE_REQUESTED = 'GET_COLLEGE_REQUESTED';
export const GET_COLLEGE_SUCCEEDED = 'GET_COLLEGE_SUCCEEDED';
export const GET_COLLEGE_FAILED = 'GET_COLLEGE_FAILED';
//一级项目
export const GET_FIRST_PROJECT_REQUESTED = 'GET_FIRST_PROJECT_REQUESTED';
export const GET_FIRST_PROJECT_SUCCEEDED = 'GET_FIRST_PROJECT_SUCCEEDED';
export const GET_FIRST_PROJECT_FAILED = 'GET_FIRST_PROJECT_FAILED';
//二级项目
export const GET_SECOND_PROJECT_REQUESTED = 'GET_SECOND_PROJECT_REQUESTED';
export const GET_SECOND_PROJECT_SUCCEEDED = 'GET_SECOND_PROJECT_SUCCEEDED';
export const GET_SECOND_PROJECT_FAILED = 'GET_SECOND_PROJECT_FAILED';
//科目
export const GET_SUBJECT_REQUESTED = 'GET_SUBJECT_REQUESTED';
export const GET_SUBJECT_SUCCEEDED = 'GET_SUBJECT_SUCCEEDED';
export const GET_SUBJECT_FAILED = 'GET_SUBJECT_FAILED';
//试卷列表
export const GET_PAPER_LIST_REQUESTED = 'GET_PAPER_LIST_REQUESTED';
export const GET_PAPER_LIST_SUCCEEDED = 'GET_PAPER_LIST_SUCCEEDED';
export const GET_PAPER_LIST_FAILED = 'GET_PAPER_LIST_FAILED';
//试卷删除
export const GET_PAPER_DELETE_REQUESTED = 'GET_PAPER_DELETE_REQUESTED';
export const GET_PAPER_DELETE_SUCCEEDED = 'GET_PAPER_DELETE_SUCCEEDED';
export const GET_PAPER_DELETE_FAILED = 'GET_PAPER_DELETE_FAILED';
//试卷上线
export const GET_PAPER_ONLINE_REQUESTED = 'GET_PAPER_ONLINE_REQUESTED';
export const GET_PAPER_ONLINE_SUCCEEDED = 'GET_PAPER_ONLINE_SUCCEEDED';
export const GET_PAPER_ONLINE_FAILED = 'GET_PAPER_ONLINE_FAILED';
//试卷下线
export const GET_PAPER_OFFLINE_REQUESTED = 'GET_PAPER_OFFLINE_REQUESTED';
export const GET_PAPER_OFFLINE_SUCCEEDED = 'GET_PAPER_OFFLINE_SUCCEEDED';
export const GET_PAPER_OFFLINE_FAILED = 'GET_PAPER_OFFLINE_FAILED';
//结束
export const GET_PAPER_CLOSE_REQUESTED = 'GET_PAPER_CLOSE_REQUESTED';
export const GET_PAPER_CLOSE_SUCCEEDED = 'GET_PAPER_CLOSE_SUCCEEDED';
export const GET_PAPER_CLOSE_FAILED = 'GET_PAPER_CLOSE_FAILED';
//试卷链接详情
export const GET_PAPER_LINK_INFO_REQUESTED = 'GET_PAPER_LINK_INFO_REQUESTED';
export const GET_PAPER_LINK_INFO_SUCCEEDED = 'GET_PAPER_LINK_INFO_SUCCEEDED';
export const GET_PAPER_LINK_INFO_FAILED = 'GET_PAPER_LINK_INFO_FAILED';
//试卷保存
export const GET_PAPER_SAVE_REQUESTED = 'GET_PAPER_SAVE_REQUESTED';
export const GET_PAPER_SAVE_SUCCEEDED = 'GET_PAPER_SAVE_SUCCEEDED';
export const GET_PAPER_SAVE_FAILED = 'GET_PAPER_SAVE_FAILED';
//试卷保存并上传
export const GET_PAPER_SAVE_ONLINE__REQUESTED = 'GET_PAPER_SAVE_ONLINE__REQUESTED';
export const GET_PAPER_SAVE_ONLINE__SUCCEEDED = 'GET_PAPER_SAVE_ONLINE__SUCCEEDED';
export const GET_PAPER_SAVE_ONLINE__FAILED = 'GET_PAPER_SAVE_ONLINE__FAILED';

export default{
    GET_COLLEGE_REQUESTED,
    GET_COLLEGE_SUCCEEDED,
    GET_COLLEGE_FAILED,
    GET_FIRST_PROJECT_REQUESTED,
    GET_FIRST_PROJECT_SUCCEEDED,
    GET_FIRST_PROJECT_FAILED,
    GET_SECOND_PROJECT_REQUESTED,
    GET_SECOND_PROJECT_SUCCEEDED,
    GET_SECOND_PROJECT_FAILED,
    GET_SUBJECT_REQUESTED,
    GET_SUBJECT_SUCCEEDED,
    GET_SUBJECT_FAILED,
    GET_PAPER_LIST_REQUESTED,
    GET_PAPER_LIST_SUCCEEDED,
    GET_PAPER_LIST_FAILED,
    GET_PAPER_DELETE_REQUESTED,
    GET_PAPER_DELETE_SUCCEEDED,
    GET_PAPER_DELETE_FAILED,
    GET_PAPER_ONLINE_REQUESTED,
    GET_PAPER_ONLINE_SUCCEEDED,
    GET_PAPER_ONLINE_FAILED,
    GET_PAPER_OFFLINE_REQUESTED,
    GET_PAPER_OFFLINE_SUCCEEDED,
    GET_PAPER_OFFLINE_FAILED,
    GET_PAPER_CLOSE_REQUESTED,
    GET_PAPER_CLOSE_SUCCEEDED,
    GET_PAPER_CLOSE_FAILED,
    GET_PAPER_LINK_INFO_REQUESTED,
    GET_PAPER_LINK_INFO_SUCCEEDED,
    GET_PAPER_LINK_INFO_FAILED
}
