export const LOGIN_REQUESTED = 'LOGIN_REQUESTED';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const USER_REQUESTED = 'USER_REQUESTED';
export const USER_SUCCEEDED = 'USER_SUCCEEDED';
export const USER_FAILED = 'USER_FAILED';

export default {
    LOGIN_REQUESTED,
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    USER_REQUESTED,
    USER_SUCCEEDED,
    USER_FAILED
}
